### ISSUE TITLE
Ameliorer le design coté webapp de la page de login

### ISSUE THREAD

**Issue by S-Stanley** [S-Stanley/ft_transcendence#5]

**Comment by Anysiia** [comment]
https://www.figma.com/file/98ruJnlUX2n7Hy0sEoC5Ov/ftranscendence?node-id=45%3A4729&t=R1Kpei6Pt7AWfZUP-0 

![image](https://user-images.githubusercontent.com/50081749/202395733-bfdd69fd-b697-4b28-a6e8-974a990c66d1.png)
